
package com.soapclient.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServicePortType", targetNamespace = "http://localhost/actu_site/soap_server.php")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.soapclient.users.ListUsersResponse
     */
    @WebMethod(action = "http://localhost/actu_site/soap_server.php#listUsers")
    @WebResult(name = "listUsersResponse", targetNamespace = "http://localhost/actu_site/soap_server.php", partName = "parameters")
    public ListUsersResponse listUsers(
        @WebParam(name = "listUsersRequest", targetNamespace = "http://localhost/actu_site/soap_server.php", partName = "parameters")
        ListUsersRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.soapclient.users.AddUserResponse
     */
    @WebMethod(action = "http://localhost/actu_site/soap_server.php#addUser")
    @WebResult(name = "addUserResponse", targetNamespace = "http://localhost/actu_site/soap_server.php", partName = "parameters")
    public AddUserResponse addUser(
        @WebParam(name = "addUserRequest", targetNamespace = "http://localhost/actu_site/soap_server.php", partName = "parameters")
        AddUserRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.soapclient.users.DeleteUserResponse
     */
    @WebMethod(action = "http://localhost/actu_site/soap_server.php#deleteUser")
    @WebResult(name = "deleteUserResponse", targetNamespace = "http://localhost/actu_site/soap_server.php", partName = "parameters")
    public DeleteUserResponse deleteUser(
        @WebParam(name = "deleteUserRequest", targetNamespace = "http://localhost/actu_site/soap_server.php", partName = "parameters")
        DeleteUserRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.soapclient.users.UpdateUserResponse
     */
    @WebMethod(action = "http://localhost/actu_site/soap_server.php#updateUser")
    @WebResult(name = "updateUserResponse", targetNamespace = "http://localhost/actu_site/soap_server.php", partName = "parameters")
    public UpdateUserResponse updateUser(
        @WebParam(name = "updateUserRequest", targetNamespace = "http://localhost/actu_site/soap_server.php", partName = "parameters")
        UpdateUserRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.soapclient.users.AuthenticateUserResponse
     */
    @WebMethod(action = "http://localhost/actu_site/soap_server.php#authenticateUser")
    @WebResult(name = "authenticateUserResponse", targetNamespace = "http://localhost/actu_site/soap_server.php", partName = "parameters")
    public AuthenticateUserResponse authenticateUser(
        @WebParam(name = "authenticateUserRequest", targetNamespace = "http://localhost/actu_site/soap_server.php", partName = "parameters")
        AuthenticateUserRequest parameters);

}
